// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Method for selecting which lots to sell (affects capital gains calculation)
 */
export type LotMethod = "Fifo" | "Lifo" | "HighestCost" | "LowestCost" | "AverageCost";
