// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pre-defined withdrawal order strategies
 */
export type WithdrawalOrder = "TaxEfficientEarly" | "TaxDeferredFirst" | "TaxFreeFirst" | "ProRata";
