// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountTypeDef } from "./AccountTypeDef";
import type { ReturnProfileRef } from "./ReturnProfileRef";

/**
 * Account definition using preset types or custom configuration
 */
export type AccountDef = { 
/**
 * Unique name for this account
 */
name: string, 
/**
 * Optional description
 */
description: string | null, 
/**
 * Account type (determines tax treatment)
 */
account_type: AccountTypeDef, 
/**
 * Initial cash balance
 */
cash: number, 
/**
 * Return profile for cash (name reference or inline)
 */
cash_return_profile: ReturnProfileRef | null, };
