// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReturnProfileRef } from "./ReturnProfileRef";

/**
 * Asset definition
 */
export type AssetDef = { 
/**
 * Unique name for this asset
 */
name: string, 
/**
 * Optional description
 */
description: string | null, 
/**
 * Initial price per unit
 */
price: number, 
/**
 * Return profile (name reference or inline definition)
 */
return_profile: ReturnProfileRef, };
