// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AmountDef } from "./AmountDef";
import type { IncomeType } from "./IncomeType";
import type { LotMethod } from "./LotMethod";
import type { WithdrawalSourceDef } from "./WithdrawalSourceDef";

/**
 * Event effect definition
 */
export type EffectDef = { "type": "Income", amount: number, to_account: string, income_type: IncomeType, gross: boolean, adjust_for_inflation: boolean, } | { "type": "Expense", amount: number, from_account: string | null, adjust_for_inflation: boolean, } | { "type": "AssetPurchase", amount: number, account: string, asset: string, adjust_for_inflation: boolean, } | { "type": "Withdrawal", amount: AmountDef, to_account: string, source: WithdrawalSourceDef, gross: boolean, lot_method: LotMethod, };
