// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReturnProfile } from "./ReturnProfile";

/**
 * Named return profile definition
 */
export type NamedReturnProfileDef = { name: string, profile: ReturnProfile, };
