// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Position (asset holding in an account)
 */
export type PositionDef = { 
/**
 * Account name (must match an AccountDef.name)
 */
account: string, 
/**
 * Asset name (must match an AssetDef.name)
 */
asset: string, 
/**
 * Number of units
 */
units: number, 
/**
 * Cost basis (total, not per unit)
 */
cost_basis: number, 
/**
 * Purchase date (YYYY-MM-DD), defaults to start_date
 */
purchase_date: string | null, };
