// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReturnProfile = "None" | { "Fixed": number } | { "Normal": { mean: number, std_dev: number, } } | { "LogNormal": { mean: number, std_dev: number, } };
