// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReturnProfile } from "./ReturnProfile";

/**
 * Reference to a return profile (by name or inline)
 */
export type ReturnProfileRef = string | ReturnProfile;
