// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tax configuration definition (simplified wrapper)
 */
export type TaxConfigDef = { 
/**
 * Federal standard deduction
 */
standard_deduction: number | null, 
/**
 * Capital gains rate
 */
capital_gains_rate: number | null, };
