// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RepeatInterval } from "./RepeatInterval";
import type { TriggerEndDef } from "./TriggerEndDef";
import type { TriggerStartDef } from "./TriggerStartDef";

/**
 * Event trigger definition
 */
export type TriggerDef = { "type": "Immediate" } | { "type": "Date", date: string, } | { "type": "Age", years: number, months: number | null, } | { "type": "Repeating", interval: RepeatInterval, start: TriggerStartDef | null, end: TriggerEndDef | null, };
