// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WithdrawalOrder } from "./WithdrawalOrder";

export type WithdrawalSourceDef = { "type": "Strategy", order: WithdrawalOrder, exclude: Array<string>, } | { "type": "AccountOrder", accounts: Array<string>, } | { "type": "Asset", account: string, asset: string, };
