// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContributionLimitPeriod } from "./ContributionLimitPeriod";

/**
 * Contribution limit configuration for an account
 */
export type ContributionLimit = { 
/**
 * Maximum contribution per period
 */
amount: number, 
/**
 * Period type for the limit
 */
period: ContributionLimitPeriod, };
