// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InflationProfile = { "type": "None" } | { "type": "Fixed" } & number | { "type": "Normal", mean: number, std_dev: number, } | { "type": "LogNormal", mean: number, std_dev: number, };
