// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How often a repeating event occurs
 */
export type RepeatInterval = "Never" | "Weekly" | "BiWeekly" | "Monthly" | "Quarterly" | "Yearly";
