// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tax treatment for an account
 */
export type TaxStatus = "Taxable" | "TaxDeferred" | "TaxFree";
