/**
 * The Review tab's API shapes, named one by one.
 *
 * Generated by `gen-bindings.sh` from `finplan_server`, like everything in
 * `./generated`; this module is the one place the Review screens and view
 * model import them from, with paths the Node test runner can resolve.
 */
export type { AppliedSuggestion } from "./generated/AppliedSuggestion.ts";
export type { ApplySuggestion } from "./generated/ApplySuggestion.ts";
export type { ChangeProblem } from "./generated/ChangeProblem.ts";
export type { ChangeProblemsBody } from "./generated/ChangeProblemsBody.ts";
export type { ChatMessage } from "./generated/ChatMessage.ts";
export type { ChatRequest } from "./generated/ChatRequest.ts";
export type { ChatRole } from "./generated/ChatRole.ts";
export type { DismissSuggestion } from "./generated/DismissSuggestion.ts";
export type { Evidence } from "./generated/Evidence.ts";
export type { PreviewSuggestion } from "./generated/PreviewSuggestion.ts";
export type { Review } from "./generated/Review.ts";
export type { ReviewRequest } from "./generated/ReviewRequest.ts";
export type { StepProblems } from "./generated/StepProblems.ts";
export type { Suggestion } from "./generated/Suggestion.ts";
export type { SuggestionCheck } from "./generated/SuggestionCheck.ts";
export type { SuggestionEstimate } from "./generated/SuggestionEstimate.ts";
export type { SuggestionKind } from "./generated/SuggestionKind.ts";
export type { SuggestionSection } from "./generated/SuggestionSection.ts";
export type { SuggestionSource } from "./generated/SuggestionSource.ts";
export type { SuggestionStatus } from "./generated/SuggestionStatus.ts";
export type { SuggestionPath } from "./generated/SuggestionPath.ts";
export type { SuggestionStep } from "./generated/SuggestionStep.ts";
export type { SuggestionThread } from "./generated/SuggestionThread.ts";
export type { ThreadStatus } from "./generated/ThreadStatus.ts";
