// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContributionLimit } from "./ContributionLimit";
import type { TaxStatus } from "./TaxStatus";

/**
 * Account type presets (maps to AccountBuilder methods)
 */
export type AccountTypeDef = { "type": "Bank" } | { "type": "TaxableBrokerage" } | { "type": "Traditional401k", contribution_limit: ContributionLimit | null, } | { "type": "Roth401k", contribution_limit: ContributionLimit | null, } | { "type": "TraditionalIra", contribution_limit: ContributionLimit | null, } | { "type": "RothIra", contribution_limit: ContributionLimit | null, } | { "type": "Hsa", contribution_limit: ContributionLimit | null, } | { "type": "Custom", tax_status: TaxStatus, contribution_limit: ContributionLimit | null, };
