// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Period type for contribution limits
 */
export type ContributionLimitPeriod = "Monthly" | "Yearly";
