// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EffectDef } from "./EffectDef";
import type { TriggerDef } from "./TriggerDef";

/**
 * Event definition
 */
export type EventDef = { 
/**
 * Event name
 */
name: string, 
/**
 * Optional description
 */
description: string | null, 
/**
 * When the event triggers
 */
trigger: TriggerDef, 
/**
 * What happens when triggered
 */
effects: Array<EffectDef>, 
/**
 * Whether this event fires only once
 */
once: boolean, };
