// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountDef } from "./AccountDef";
import type { AssetDef } from "./AssetDef";
import type { EventDef } from "./EventDef";
import type { InflationProfile } from "./InflationProfile";
import type { NamedReturnProfileDef } from "./NamedReturnProfileDef";
import type { PositionDef } from "./PositionDef";
import type { TaxConfigDef } from "./TaxConfigDef";

/**
 * API request to create a simulation (name-based, no IDs required)
 */
export type SimulationRequest = { 
/**
 * Simulation name
 */
name: string, 
/**
 * Optional description
 */
description: string | null, 
/**
 * Start date (YYYY-MM-DD)
 */
start_date: string | null, 
/**
 * Number of years to simulate
 */
duration_years: number, 
/**
 * Birth date for age-based triggers (YYYY-MM-DD)
 */
birth_date: string | null, 
/**
 * Named return profiles (referenced by name in assets)
 */
return_profiles?: Array<NamedReturnProfileDef>, 
/**
 * Inflation model
 */
inflation_profile: InflationProfile | null, 
/**
 * Tax configuration
 */
tax_config: TaxConfigDef | null, 
/**
 * Account definitions (name-based)
 */
accounts?: Array<AccountDef>, 
/**
 * Asset definitions (name-based)
 */
assets?: Array<AssetDef>, 
/**
 * Initial positions (references accounts/assets by name)
 */
positions?: Array<PositionDef>, 
/**
 * Event definitions (name-based references)
 */
events?: Array<EventDef>, };
