// State tax rate data for reference
export const US_STATES = [
    { code: "AL" as const, name: "Alabama", topRate: 5.0 },
    { code: "AK" as const, name: "Alaska", topRate: 0 },
    { code: "AZ" as const, name: "Arizona", topRate: 4.5 },
    { code: "AR" as const, name: "Arkansas", topRate: 5.5 },
    { code: "CA" as const, name: "California", topRate: 13.3 },
    { code: "CO" as const, name: "Colorado", topRate: 4.4 },
    { code: "CT" as const, name: "Connecticut", topRate: 6.99 },
    { code: "DE" as const, name: "Delaware", topRate: 6.6 },
    { code: "FL" as const, name: "Florida", topRate: 0 },
    { code: "GA" as const, name: "Georgia", topRate: 5.75 },
    { code: "HI" as const, name: "Hawaii", topRate: 11.0 },
    { code: "ID" as const, name: "Idaho", topRate: 5.8 },
    { code: "IL" as const, name: "Illinois", topRate: 4.95 },
    { code: "IN" as const, name: "Indiana", topRate: 3.23 },
    { code: "IA" as const, name: "Iowa", topRate: 6.0 },
    { code: "KS" as const, name: "Kansas", topRate: 5.7 },
    { code: "KY" as const, name: "Kentucky", topRate: 4.5 },
    { code: "LA" as const, name: "Louisiana", topRate: 4.25 },
    { code: "ME" as const, name: "Maine", topRate: 7.15 },
    { code: "MD" as const, name: "Maryland", topRate: 5.75 },
    { code: "MA" as const, name: "Massachusetts", topRate: 5.0 },
    { code: "MI" as const, name: "Michigan", topRate: 4.25 },
    { code: "MN" as const, name: "Minnesota", topRate: 9.85 },
    { code: "MS" as const, name: "Mississippi", topRate: 5.0 },
    { code: "MO" as const, name: "Missouri", topRate: 5.3 },
    { code: "MT" as const, name: "Montana", topRate: 6.75 },
    { code: "NE" as const, name: "Nebraska", topRate: 6.84 },
    { code: "NV" as const, name: "Nevada", topRate: 0 },
    { code: "NH" as const, name: "New Hampshire", topRate: 0 },
    { code: "NJ" as const, name: "New Jersey", topRate: 10.75 },
    { code: "NM" as const, name: "New Mexico", topRate: 5.9 },
    { code: "NY" as const, name: "New York", topRate: 10.9 },
    { code: "NC" as const, name: "North Carolina", topRate: 4.75 },
    { code: "ND" as const, name: "North Dakota", topRate: 2.9 },
    { code: "OH" as const, name: "Ohio", topRate: 3.99 },
    { code: "OK" as const, name: "Oklahoma", topRate: 4.75 },
    { code: "OR" as const, name: "Oregon", topRate: 9.9 },
    { code: "PA" as const, name: "Pennsylvania", topRate: 3.07 },
    { code: "RI" as const, name: "Rhode Island", topRate: 5.99 },
    { code: "SC" as const, name: "South Carolina", topRate: 6.5 },
    { code: "SD" as const, name: "South Dakota", topRate: 0 },
    { code: "TN" as const, name: "Tennessee", topRate: 0 },
    { code: "TX" as const, name: "Texas", topRate: 0 },
    { code: "UT" as const, name: "Utah", topRate: 4.85 },
    { code: "VT" as const, name: "Vermont", topRate: 8.75 },
    { code: "VA" as const, name: "Virginia", topRate: 5.75 },
    { code: "WA" as const, name: "Washington", topRate: 0 },
    { code: "WV" as const, name: "West Virginia", topRate: 6.5 },
    { code: "WI" as const, name: "Wisconsin", topRate: 7.65 },
    { code: "WY" as const, name: "Wyoming", topRate: 0 },
];

export function getStateTaxRate(stateCode: string): number {
    const state = US_STATES.find((s) => s.code === stateCode);
    return state ? state.topRate / 100 : 0;
}
