#!/usr/bin/env bash
#
# Regenerate the TypeScript bindings for the finplan_server API types.
#
# The types themselves are the source of truth: every request/response struct in
# `crates/finplan_server/src/{api,auth,error}`, the plan specs in
# `crates/finplan_plan/src/specs` and the engine's own shapes in
# `crates/finplan_wasm/src` derives `ts_rs::TS`, and ts-rs writes one
# `.ts` file per type. Run this after changing any of them; the
# result is committed, so `git diff --exit-code web/lib/api/generated` in CI
# catches bindings that have drifted from the server.
#
# The i64 -> number setting lives in .cargo/config.toml. Its export directory is
# a scratch one under target/, so that a plain `cargo test` leaves the committed
# files alone; this script points ts-rs at the web app instead.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="$root/web/lib/api/generated"

# Stale files would otherwise survive a type being renamed or deleted.
rm -rf "$out"
mkdir -p "$out"
export TS_RS_EXPORT_DIR="$out"

# Types that live in finplan_plan are exported by that crate's own tests, so
# it needs its own run (and the same formatting feature).
cargo test --manifest-path "$root/Cargo.toml" -p finplan_server \
    --features ts-format --lib export_bindings -- --quiet
cargo test --manifest-path "$root/Cargo.toml" -p finplan_plan \
    --features ts-format --lib export_bindings -- --quiet
# ...and so are the few shapes the browser engine adds (errors, read queries).
cargo test --manifest-path "$root/Cargo.toml" -p finplan_wasm \
    --features ts-format --lib export_bindings -- --quiet

# ts-rs emits a file per type but no barrel, and 50-odd deep imports in the
# client would be unreadable.
index="$out/index.ts"
{
    echo "// Generated by scripts/gen-bindings.sh. Do not edit this file manually."
    echo
    for file in "$out"/*.ts; do
        name="$(basename "$file" .ts)"
        [ "$name" = "index" ] && continue
        echo "export type { $name } from \"./$name\";"
    done
} > "$index"

echo "wrote $(find "$out" -name '*.ts' | wc -l | tr -d ' ') files to ${out#"$root"/}"
